[versions]
# Project
kotlin = "1.9.25"
java = "17"

# Spring
spring-boot = "3.5.5"
spring-dependency-management = "1.1.7"
spring-test = "6.2.10"

# Testcontainers
testcontainers = "2.0.2"

# Test
kotest = "5.9.1"
kotest-extensions-spring = "1.3.0"

# Build plugins
maven-publish = "0.28.0"

[libraries]
# Kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }

# Spring Boot
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring-test" }

# Testcontainers
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
testcontainers-mongodb = { module = "org.testcontainers:testcontainers-mongodb", version.ref = "testcontainers" }

# Database
postgresql = { module = "org.postgresql:postgresql" }

# Test
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-extensions-spring = { module = "io.kotest.extensions:kotest-extensions-spring", version.ref = "kotest-extensions-spring" }

[bundles]
kotest = ["kotest-runner-junit5", "kotest-assertions-core", "kotest-extensions-spring"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
